name: fluxoComAmbiente

on:
  workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: build
        run: echo construindo aplicação
    
  deploy-dev:
      runs-on:  ubuntu-latest
      environment:
         name: developer
      needs: build
      steps:
         - name: developer
           run: echo analisando feature
